sudo: required

language: bash

install:
  - sudo apt-get update -qy
  - sudo apt-get install -y jq
  - wget https://github.com/tus/tusd/releases/download/v1.0.0/tusd_linux_amd64.tar.gz
  - tar xzf tusd_linux_amd64.tar.gz

before_script:
  - chmod +x tusc.sh
  - chmod +x tusd_linux_amd64/tusd

script:
  - bash -n ./tusc.sh
  - 'tusd_linux_amd64/tusd --upload-dir ~/.tusd-data --base-path /tus/ > /dev/null 2>&1 &'
  - './tusc.sh -H 0:1080 -f tusd_linux_amd64.tar.gz -a sha256 -b /tus/'
  - 'URL=$(./tusc.sh -H 0:1080 -f tusd_linux_amd64.tar.gz -a sha256 -b /tus/ -L)'
  - 'wget $(echo $URL | grep -o -E "http://[a-z0-9\.\:\/]+") -O tusd_linux_amd64.tar.gz1'
  - '[[ "$(md5sum tusd_linux_amd64.tar.gz1)" == "$(md5sum tusd_linux_amd64.tar.gz)1" ]] || exit 1'
